@startuml

start

while ( счетчик меньше 11) is (да)
: введите число <
endwhile (нет)

while ( счетчик меньше 11) is (да)
	: результат = sqrt(fabs(x)) + 5 * pow(x, 3);
	if(результат > 400) then (да)
		: вывод "результат 
		больше 400" >
		else
			: вывод 
			результат >
			endif
endwhile (нет)
end


@enduml